# fly.toml app configuration file generated for bee-storm on 2023-08-15T20:46:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bee-storm"
primary_region = "cdg"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
  cpus = 1
  processes = ["app"]

[mounts]
  source = "bee-storm-data"
  destination = "/data'